### ISSUE TITLE
Customizing card components

### ISSUE THREAD

**Issue by rimkerb** [Adyen/adyen-flutter#160]
Hello,
I am trying to integrate this sdk into a flutter app and was wondering if there is any proposed solution in customizing the `CardComponents` currently? 
As far as the documentations go on the native libraries, that option is available albeit slightly vague.
For Android -> Overriding the styles of all components in styles.xml/strings.xml, which is still possible to do.
on iOS -> adding the `FormComponentStyle()` on the cardComponent itself.
However the iOS styling is done manually when initiating the native component and the style object is not exposed in the current version of the library as far as I can see or perhaps this is coming in a future release?

As a side question, is there a possibility to somehow invoke the `onSubmit` button without using the pre-built button?
A common use case would be for devs to build their own custom button on the flutter side and invoke it manually.

**Comment by rimkerb** [comment]
Hey, thanks for the answer,

Is there any indication on when the beta release might roll out?

**Comment by Robert-SD** [comment]
Hey @rimkerb, 

You're welcome, I am happy to help out. 

We plan to release the beta at the end of May / in the beginning of June. We currently don’t have a specific date because we want to finish some features first and smaller adjustments before releasing the beta. 
I will update this issue and notify you when the release is available.
