### ISSUE TITLE
Alpha > Beta > GA

### ISSUE THREAD

**Issue by matmicro** [Adyen/adyen-flutter#165]
Is it possible to have a better view about the current alpha version and the next steps:
- When is planned to be BETA released ?
- When is expected to be GA ?

From which version could we expect to implement this on a LIVE version of our apps ?

Regards

**Comment by camil-adyen** [comment]
HI @matmicro,

Thanks for reaching out. 

We're currently working towards the BETA release and our goal is to have it ready by the beginning of June. After that, we'll work on increasing the test coverage before we release the official v1. We aim to release v1 together with official documentation by the end of June. 

As for using the SDK in LIVE - several merchants are already processing LIVE payments using our Flutter SDK. We consider all the features and functionalities that are currently available in the alpha version to be stable. The reason we still label it as alpha is because we do not yet support all the functionality we want the official v1 to support. 

If the current alpha version supports everything you need to process payments, you can already implement the SDK in the LIVE version of your app. 

Hope this answers your questions.

Best, 
Camil

**Comment by camil-adyen** [comment]
Hi @matmicro,

The v1 release will include the following new features:

- Support for API-only merchant to encrypt card details (CSE)
- More standalone Components for payment methods (PayPal, Klarna, etc.)
- High level styling possibilities 
- Minor code refactoring 
- Increased test coverage

We don't own nor maintain the library you refer to. Feel free to compare it with our current [alpha version](https://pub.dev/packages/adyen_checkout).

**Comment by alextarrago** [comment]
Hi @camil-adyen,

First things first, thanks for the amazing work you guys are doing.

We are planning to release a high-impact ecommerce app that relies on a custom Flutter Adyen integration (using platform channels) for both iOS and Android. We have a new requirement to implement PayPal as a global payment method inside the checkout, and we are wondering if our timeline can align with your roadmap for the release of this Library (V1).

Is the end of June still the deadline for V1 to go live?

**Comment by camil-adyen** [comment]
Hi @alextarrago,

Thanks a lot and nice to hear that you will use our SDK! 

We're performing the final tests in the beginning of next week. If all goes well, the plan is to release v1 including official documentation before the end of June. The current BETA version already supports Paypal, so feel free to have a look and provide feedback where necessary. 

I'll give an update in this thread case of any new developments!

**Comment by camil-adyen** [comment]
The official v1 of Flutter Drop-in/Components has now been released on [pud.dev](https://pub.dev/packages/adyen_checkout)
