### ISSUE TITLE
3DS not triggered - payment refused

### ISSUE THREAD

**Issue by matmicro** [Adyen/adyen-flutter#204]
When using Dropin:
```
adyen.DropInConfiguration(
        environment: adyen.Environment.europe,
        clientKey: ...,
        countryCode: ...,
        shopperLocale: ...,
        amount: adyen.Amount(
            value: ...,
            currency: ...),
      );
```

I am facing payments refused:
```
Acquirer response: [Authentication required (65 : Authentication required)]
Shopper interaction: Ecommerce
CVC/CVV: Supplied, Doesn''t match (N)
```

My Merchant account is well configured with `Always` propose 3DSecure.

When user type in the card number and validate, the 3DS2 is not triggered, and payment is refused immediately.
This is with Mastercards ecards. I can provide PSP if needed.

Is that a bug from the Dropin ?
How to fix this ?

Thanks and regards

**Comment by Robert-SD** [comment]
Hi @matmicro, 
thanks for opening this issue as well. I will look into this but might need to involve our customer support team. 
Will come back with more information.

**Comment by Robert-SD** [comment]
@matmicro, I think reaching out to the support team or to your account manager is the right way. Could you ask to involve me as well so we could setup a call where we go through the different questions?

**Comment by Robert-SD** [comment]
@matmicro unfortunately I do not want to expose my work email here. Hope that is ok. 
Could you ask the support to add me to the loop? I would like to help out so we can resolve the issues asap.

**Comment by BenjaminStoeberl** [comment]
Hey @Robert-SD , thanks for the quick response!

We talked with the support team and it seems the reason in our case is that we are missing the browserInfo parameter. For us it's currently a bit unclear how to exactly provide it, since our requests against [/payments](https://docs.adyen.com/api-explorer/Checkout/71/post/payments#request-authenticationData) originate from the mobile client and not a browser. We will try to solve this question with support.
