### ISSUE TITLE
Preselect ApplePay when unique Payment Method

### ISSUE THREAD

**Issue by alextarrago** [Adyen/adyen-flutter#221]
**Bug Description**
When selecting Apple Pay as the only available payment method and setting `skipListWhenSinglePaymentMethod` to `true`, the payment method selection screen is still displayed instead of skipping directly to the Apple Pay payment sheet.

**Expected Behavior**
The Apple Pay payment sheet should be displayed directly, without requiring the user to click through the payment method selection screen.

**Comment by alextarrago** [comment]
Hi @Robert-SD , 
Thanks for the fast reply. Correct, we are using the Advanced Flow using Drop-In integration setting the `skipListWhenSinglePaymentMethod` to `true`. 

We've managed to only show Apple Pay on the Payment Option Sheet when needed, but we want to Skip that previous screen and go directly to the Apple Pay native payment sheet.

Can we use Drop-In for CC and Components for Apple Pay in the same project?

**Comment by Robert-SD** [comment]
Thanks for sharing your integration @alextarrago. 
Showing the Apple Pay button is unfortunately required before launching the native Apple Pay payment sheet. Therefore, it is not possible to launch it directly.

In order to confirm your use case, I simulated the scenario and recorded a quick demo video. Does this flow look like yours? 

I will also check the combination of Drop-In for CC and the Apple Pay Component. In theory it should be possible because they are independent from another. Nevertheless, we have not added this setup in the example app yet. Will reply with an update soon.

https://github.com/user-attachments/assets/3a63b724-d233-4073-b4d9-a06f10c7a4cd

**Comment by alextarrago** [comment]
Thanks @Robert-SD we will investigate on the Drop-In + CC implementation. If we get it working I'll update on that :)

**Comment by Robert-SD** [comment]
Sure! Thank you very much 🙂
Will also investigate regarding an integration of both.

**Comment by Robert-SD** [comment]
@alextarrago I just want to share with you a quick result after trying out the combination of Drop-In and Apple Pay. It looks promising and I am really curious about your feedback and update :) 

The "Pay with Cards" button uses Drop-In where the Apple Pay button is the component. The payment methods list is filtered accordingly so that Drop-In is only populated with the "scheme" entry and the component with the "applepay" entry. Both use the same AdvancedCheckout object. 

Please let me know if you have any questions 🙂  

https://github.com/user-attachments/assets/4ffa1fe8-c12b-4d53-b2f4-781944356c36

**Comment by alextarrago** [comment]
Hi @Robert-SD , I was planning to do these tests tomorrow. I'll share the results with you. Can you share this PoC with us somehow?

Thanks!

**Comment by Robert-SD** [comment]
Hi @alextarrago, 
sure, I created a new branch. You can find the PoC [here](https://github.com/Adyen/adyen-flutter/blob/example/DropInComponentCombination/example/lib/screens/component/multi_component/component_dropin_advanced_screen.dart). 
Please let me know if you have any questions. I'm very interested in your findings :)

**Comment by alextarrago** [comment]
Thanks @Robert-SD , we got the same results in terms of implementation. We are just facing an issue in our Components implementation, we are getting `AdyenCheckout: Apple pay is not available on this device.` when trying to render the Button... stuck there for today.

**Comment by Robert-SD** [comment]
Hey @alextarrago, could you share if Apple Pay is available one the test device or do you use a simulator? The message appears when the Apple Pay availability fails. We could also analyze the Apple Pay component configuration and the provided paymentMethod.

**Comment by alextarrago** [comment]
Yes, that's the weird thing, it was working with drop-in implementation.
```
Widget _buildAdyenApplePayAdvancedComponent(
    BuildContext context,
  ) {
    final ApplePayComponentConfiguration applePayComponentConfiguration = ApplePayComponentConfiguration(
      environment: Environment.test,
      clientKey: "****",
      countryCode: "**",
      amount: Amount(value: ****, currency: "***"),
      applePayConfiguration: _createApplePayConfiguration(),
    );

    final AdvancedCheckout advancedCheckout = AdvancedCheckout(
      onSubmit: _checkoutBloc.onSubmit,
      onAdditionalDetails: _checkoutBloc.onAdditionalDetails,
    );
    PaymentMethodsResponse? paymentMethod = _checkoutBloc.paymentMethods();
    if (paymentMethod == null) {
      return SizedBox.shrink();
    }

    return Padding(
      padding: const EdgeInsets.fromLTRB(10, 0, 10, 0),
      child: AdyenApplePayComponent(
        configuration: applePayComponentConfiguration,
        paymentMethod: json.decode(
            '{"paymentMethods":[{"brands":["mc","visa","amex"],"configuration":{"merchantId":"***","merchantName":"****"},"name":"Apple Pay","type":"applepay"}]}'),
        checkout: advancedCheckout,
        style: ApplePayButtonStyle(
          theme: ApplePayButtonTheme.black,
          type: ApplePayButtonType.buy,
        ),
        width: double.infinity,
        height: 56,
        onPaymentResult: (paymentResult) {
          _checkoutBloc.evaluateResponse(paymentResult);
        },
      ),
    );
  }

  ApplePayConfiguration _createApplePayConfiguration() {
    return ApplePayConfiguration(
      merchantId: "merchant.***.***",
      merchantName: "***",
      allowOnboarding: true,
      applePaySummaryItems: _getApplePayItems()
    );
  }
```

**Comment by Robert-SD** [comment]
Thanks for sharing your code @alextarrago. 
I might spotted it so would be great if you could try a small adjustment. The `paymentMethod` parameter of the `AdyenApplePayComponent` expects the single Apple Pay payment method JSON instead of the paymentMethods array. Please let me know if this resolves the error message.

```dart
AdyenApplePayComponent(
        configuration: applePayComponentConfiguration,
        paymentMethod: json.decode(
            '{"brands":["mc","visa","amex"],"configuration":{"merchantId":"***","merchantName":"****"},"name":"Apple Pay","type":"applepay"}'),
        checkout: advancedCheckout,
        style: ApplePayButtonStyle(
          theme: ApplePayButtonTheme.black,
          type: ApplePayButtonType.buy,
        ),
        width: double.infinity,
        height: 56,
        onPaymentResult: (paymentResult) {
          _checkoutBloc.evaluateResponse(paymentResult);
        },
      )
```

**Comment by alextarrago** [comment]
You are absolutely correct. To summarize, we have successfully implemented both Apple Pay and Google Pay using Components, while the remainder of the payment methods were integrated using Drop-in. We are planning to launch in four countries next week. Thank you for your assistance 👍
