### ISSUE TITLE
Initialize card component with prefill value

### ISSUE THREAD

**Issue by aJIEw** [Adyen/adyen-flutter#225]
**Is your feature request related to a problem? Please describe.**
After the user submits invalid card info (wrong expiry date/security code, etc) and the card component gets re-initiazlied, the previous inputs get lost. We want to be able to retain that info so that the user won't need to input everything again.

So basically we need to have a method to listen for the changes of the input data, and also to initialize the card component with prefill values.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Robert-SD** [comment]
Hi @aJIEw, thanks for the enhancement suggestion. We will discuss this internally but I have the feeling that we cannot offer this functionality. The card component does not provide raw card data because it is not recommended to retain/store card data due to security and compliance reasons. 
Maybe [tokenization](https://docs.adyen.com/online-payments/tokenization/) might help you to improve the checkout experience of your customers. The Flutter SDK supports stored (tokenized) cards.

**Comment by Robert-SD** [comment]
Hello @aJIEw, 
after discussing this feature, we cannot offer a method for exposing input data. This would violate compliance policies.
As mentioned and to reduce customer friction, you can use stored cards. For that, please have a look at [tokenization](https://docs.adyen.com/payment-methods/cards/flutter-component/#stored-card-payments) for the stored card component.

**Comment by aJIEw** [comment]
> after discussing this feature, we cannot offer a method for exposing input data. This would violate compliance policies.
> As mentioned and to reduce customer friction, you can use stored cards. For that, please have a look at [tokenization](https://docs.adyen.com/payment-methods/cards/flutter-component/#stored-card-payments) for the stored card component.

Thanks for the info, we have already implemented the tokenized card payment, this is just a UX improvement we want to have for new card payments, but again thanks for your reply.
