### ISSUE TITLE
Not able to Run app in Android

### ISSUE THREAD

**Issue by palashpandya592** [Adyen/adyen-flutter#239]
**Describe the bug**
Not able to integrate payment gateway into the app example is working fine.
**To Reproduce**
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.enableConsoleLogging"., null, null)
E/flutter (13324): #0      CheckoutPlatformInterface.enableConsoleLogging (package:adyen_checkout/src/generated/platform_api.g.dart:1673:7)
E/flutter (13324): <asynchronous suspension>
E/flutter (13324): 
E/flutter (13324): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.enableConsoleLogging"., null, null)
E/flutter (13324): #0      CheckoutPlatformInterface.enableConsoleLogging (package:adyen_checkout/src/generated/platform_api.g.dart:1673:7)
E/flutter (13324): <asynchronous suspension>

**Comment by Robert-SD** [comment]
Hi @palashpandya592, 
thank you for reaching out. I would like to help you resolving the issue. 

Could you please share your intended integration? What kind of flow do you plan to use? Is it Drop-In with the session or the advanced flow?

As a first check, could you verify that your MainActivity of the Android app is subclassing the `FlutterFragmentActivity` instead of the default `FlutterActivity`. This is our [example](https://github.com/Adyen/adyen-flutter/blob/main/example/android/app/src/main/kotlin/com/adyen/checkout/flutter/example/MainActivity.kt) MainActivity.

**Comment by palashpandya592** [comment]
@Robert-SD Thanks now i'm able to run code and it's working fine.
Can you please add this in Readme so it easy to know everyone about changes.

**Comment by palashpandya592** [comment]
> @Robert-SD Thanks now i'm able to run code and it's working fine. Can you please add this in Readme so it easy to know everyone about changes.

**Comment by Robert-SD** [comment]
Perfect, glad it worked! 
We can add a link to the setup [step](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Flutter&integration=Drop-in&tab=android_2#step-3-add-drop-in-to-your-app) in our docs. Thanks for the suggestion! 💚
