### ISSUE TITLE
adyen_checkout v: 1.0.1 isn't working with Android devices

### ISSUE THREAD

**Issue by ahmedtamerbks** [Adyen/adyen-flutter#265]
When testing Adyen checkout on IOS emulator  it's working fine, but when test it on Android emulator and device is not working and has error like: 
PlatformException(channel-error, Unable to establish connection on channel: 
"dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.createSession"., null, null)
D/EGL_emulation(23348): app_time_stats: avg=616.69ms min=11.66ms max=7828.85ms count=13

Error on line: 
AdyenCheckout.session.create(
        sessionId: sessionId,
        sessionData: sessionData,
        configuration: dropInConfiguration,
      )
      
Flutter v: 3.22.2
environment: sdk: '>=3.4.3 <4.0.0'

**Comment by Robert-SD** [comment]
Hi @ahmedtamerbks, 
thanks for raising your question. We would like to help out. 
As a first step, could you verify that your MainActivity of the Android app is subclassing the FlutterFragmentActivity instead of the default FlutterActivity. This is our [example](https://github.com/Adyen/adyen-flutter/blob/main/example/android/app/src/main/kotlin/com/adyen/checkout/flutter/example/MainActivity.kt) MainActivity.

**Comment by ahmedtamerbks** [comment]
Hi @Robert-SD,
Thanks for your fast reply.
I added FlutterFragmentActivity to the MainActivity and it's solved.

**Comment by Robert-SD** [comment]
Your welcome! Glad the suggestion helped.
