### ISSUE TITLE
Adyen Android Bug

### ISSUE THREAD

**Issue by Nimr-Prestigia** [Adyen/adyen-flutter#270]
**Describe the bug**
When I compiled the app on Android to test it, I got an error once I can any method that has a channel call to the main API in Kotlen 

```
 PlatformException(channel-error, Unable to establish connection on channel: "dev.flutter.pigeon.adyen_checkout.CheckoutPlatformInterface.createSession"., null, null)
```

I ran the example, and it worked, I run my app on iOS it worked too, but once on Android it didn't work, but the example did, now I don't know what config I should do to make it work.

**Comment by Robert-SD** [comment]
Hello @Nimr-Prestigia, 
I would like to help resolving your Android issue. 
Could you verify that your MainActivity of the Android app is subclassing the FlutterFragmentActivity instead of the default FlutterActivity? This is our [example](https://github.com/Adyen/adyen-flutter/blob/main/example/android/app/src/main/kotlin/com/adyen/checkout/flutter/example/MainActivity.kt) MainActivity.

**Comment by Nimr-Prestigia** [comment]
I just saw it in the example, I wonder why, ok I will change it to see, thanks

**Comment by Robert-SD** [comment]
We need the FlutterFragmentActivity because it supports FragmentActivity. The normal FlutterActivity is not a FragmentActivity. Please let me know if it works.

**Comment by Nimr-Prestigia** [comment]
Thanks, it worked I had to change it to FlutterFragmentActivity
