### ISSUE TITLE
Missing 'reason' in PaymentSessionFinished (drop-in)

### ISSUE THREAD

**Issue by brynjargauti** [Adyen/adyen-flutter#283]
I have been using the startDropIn() method of the adyen package:

final PaymentResult paymentResult = await AdyenCheckout.session.startDropIn(
    dropInConfiguration: dropInConfiguration,
    checkout: sessionCheckout,
);

I've encountered an issue where a user gets a fraud score of 100 and therefore the payment is cancelled.
As a result the user gets a paymentResult of type "PaymentSessionFinished", with a resultCode "Cancelled" but the refusal reason is missing. 

Can you include the 'reason' attribute in the response so that I can inform the user why his payment was cancelled?

According to the adyen docs there should be a reason provided in the response:

" Post-authorization checks include data received by issuers, such as AVS data and CVC codes or liability shift. If pre-authorisation and post-authorization check(s) adds up to 100 or more, the transaction will receive resultCode: Cancelled with refusalReason: FRAUD-CANCELLED. "

https://help.adyen.com/knowledge/risk/fraud-score/how-does-the-fraud-score-work

**Comment by Robert-SD** [comment]
Hello @brynjargauti,
Thank you for raising the question regarding the missing refusalReason for our sessions integration. 

The SDK does not provide the refusalReason to minimize risk exposure. We want to prevent malicious clients so that they are not able to make any conclusions about payment data through a failing payment.

Nevertheless, you should be able to get the refusalReason through a [webhook](https://docs.adyen.com/development-resources/webhooks/) for processing it on your server.

Please let me know if you need additional information to obtain refusal reasons.

**Comment by brynjargauti** [comment]
Hello @Robert-SD ,
Thanks for the clarification, I'll look into using a webhook to obtain the refusal reason!
