### ISSUE TITLE
3ds redirect - no onPaymentResult when closing the webpage by app bar exit button or system navigation

### ISSUE THREAD

**Issue by drekyyy** [Adyen/adyen-flutter#296]
**Describe the bug**
When closing web 3ds (redirect) by using the top left X button in app bar or android system navigation (bottom bar), onPaymentResult is not called

**To Reproduce**
initiate payment with credit card or gpay test cards choosing any 3ds card that redirects, then once the webpage is loaded, close it through one of previously mentioned methods

**Expected behavior**
Id expect the same behavior as the 'Cancel simulator' button, below the 'Continue' button - it returns a PaymentError.

**Video**

https://github.com/user-attachments/assets/4f30ef3c-9595-4c49-a119-995744a185e5

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A13
 - OS: Android 14

**Comment by Robert-SD** [comment]
Hey @drekyyy, 
Thanks for spotting this behavior and providing a video. I was also able to reproduce the behavior on the example app as well. The loading bottom sheet is not being displayed to cancel the ongoing payment and to achieve the expected behavior of receiving a PaymentCancelledByUser payment result. 
I’ve added a small PR to show the loading bottom sheet. Feel free to watch the video with the new behavior. It will be part of the next release.
Thanks again for your help! 💚

https://github.com/user-attachments/assets/916fa5f9-e125-491a-9efd-027ef640e091
