### ISSUE TITLE
Add support for iDEAL Instant Component

### ISSUE THREAD

**Issue by MickaelTitecaTAO** [Adyen/adyen-flutter#322]
**Describe the bug**
When I want to pay via iDEAL on Android, I have the following error : "Unsupported payment method ideal".
On iOS, the same code works.

Merchant account : supports the new iDEAL configuration (mandatory for April 1st 2025)
Environment : Environment.test
Country code : NL

**To Reproduce**
I reproduced the bug using the exemple project.
In _InstantAdvancedComponentScreen_, you can replace _klarna_ with _ideal_. 
Then I click on iDEAL button : on Android, an error is thrown by the SDK.

**Expected behavior**
On iOS, iDEAL's webview is displayed as expected.

**Screenshots**
Android (Pixel 4 API 34 emulator) : 
<img src="https://github.com/user-attachments/assets/bb20dea0-46f7-4f5b-9289-816f456dc9c0" height="600">

iOS (iPhone 15 Pro Max - iOS 17.5 simulator): 
<img src="https://github.com/user-attachments/assets/ef520179-74c6-45df-be23-346e1131d939" height="600">

**Comment by Robert-SD** [comment]
Hello @MickaelTitecaTAO, 
Thank you for reaching out and providing a detailed problem description with screenshots. Unfortunately, the Instant Component does not yet fully support the iDEAL payment method. Only Drop-In supports the new iDEAL flow at the moment. We are actively working on the component support and we plan to release the feature in Q1 2025.

We appreciate your patience and will reach out when the release is available. Please feel free to reach out if you have any further questions.

**Comment by MickaelTitecaTAO** [comment]
@Robert-SD Do I have to use Drop-In to add iDEAL to the payment method list even if I want to use the old flow ? Instant Component doesn't seem to support the old flow too for Android. I want to support iDEAL for January 2025.

Thanks a lot for your help.

**Comment by Robert-SD** [comment]
Hello @MickaelTitecaTAO, 
we've looked into the code and opened a PR to add the new iDAEL flow to our instant component on Android. When merged, it will be part of the new release in the beginning of 2025. Our current release does not support iDEAL as a component whether it is the new or old flow. Drop-In is therefore the only way and supports the old and new flow.

You could also try out the new solution by using our Github repo [directly](https://docs.flutter.dev/packages-and-plugins/using-packages#dependencies-on-unpublished-packages). But please keep in mind that this is not recommended for your production app because we actively work on the branches.

**Comment by MickaelTitecaTAO** [comment]
Hi @Robert-SD,

I've tested commit _90b81b2646451104312fda6c3ed0be6acb61973c_ and Instant Component works on Android on my project. My merchant account has the old flow. I had to update Kotlin version to 2.0.0 in order to run the app.
I'm waiting for a stable release to use it.

Thanks a lot for putting iDEAL support as one of your top priorities for the next release !

**Comment by Robert-SD** [comment]
Awesome, thanks for testing it! 👍 
Indeed, the Kotlin version as well as Gradle will need an updated because we also updated to the latest native Android SDK v5.8.0. Kotlin v1.8.22 will be the new minimum version together with AGP 8.1 and Gradle v8.
